/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Attendee : Meeting Attendee
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Attendee {
    #[serde(rename = "ClientType")]
    pub client_type: String,
    #[serde(rename = "FullName")]
    pub full_name: String,
    #[serde(rename = "HasJoinedVoice")]
    pub has_joined_voice: bool,
    #[serde(rename = "HasVideo")]
    pub has_video: bool,
    #[serde(rename = "InternalUserID")]
    pub internal_user_id: String,
    #[serde(rename = "IsListeningOnly")]
    pub is_listening_only: bool,
    #[serde(rename = "IsPresenter")]
    pub is_presenter: bool,
    #[serde(rename = "Role")]
    pub role: String,
    #[serde(rename = "UserID")]
    pub user_id: String,
}

impl Attendee {
    /// Meeting Attendee
    pub fn new(
        client_type: String,
        full_name: String,
        has_joined_voice: bool,
        has_video: bool,
        internal_user_id: String,
        is_listening_only: bool,
        is_presenter: bool,
        role: String,
        user_id: String,
    ) -> Attendee {
        Attendee {
            client_type,
            full_name,
            has_joined_voice,
            has_video,
            internal_user_id,
            is_listening_only,
            is_presenter,
            role,
            user_id,
        }
    }
}
