/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AttendeesLimitSettings : Limits
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttendeesLimitSettings {
    /// Limit of overall attendees for a frontend.
    #[serde(rename = "limit")]
    pub limit: i32,
}

impl AttendeesLimitSettings {
    /// Limits
    pub fn new(limit: i32) -> AttendeesLimitSettings {
        AttendeesLimitSettings { limit }
    }
}
