/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BackendPatch : Backend Update
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BackendPatch {
    /// The desired state of the node. If none given, it will be assumed 'ready'.  **Example**: `ready`
    #[serde(rename = "admin_state", skip_serializing_if = "Option::is_none")]
    pub admin_state: Option<AdminState>,
    /// The last time we heared from the node agent.
    #[serde(rename = "agent_heartbeat", skip_serializing_if = "Option::is_none")]
    pub agent_heartbeat: Option<String>,
    /// The identifier of the agent running on the backend. Used for backend authorization and agent authentication.
    #[serde(
        rename = "agent_ref",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub agent_ref: Option<Option<String>>,
    /// Number of participants in meetings on the backend.
    #[serde(rename = "attendees_count", skip_serializing_if = "Option::is_none")]
    pub attendees_count: Option<i32>,
    #[serde(rename = "bbb", skip_serializing_if = "Option::is_none")]
    pub bbb: Option<Box<models::BackendConfig>>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The last error that happend. For example destination host not reachable.
    #[serde(
        rename = "last_error",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_error: Option<Option<String>>,
    /// The amount of milliseconds when polling the current node state.
    #[serde(rename = "latency", skip_serializing_if = "Option::is_none")]
    pub latency: Option<i32>,
    /// The load factor influences the probability of selecting this backend when a meeting is created. The amount of meetings and attendees on the node will be multiplied with the load factor, when calculating the backend stress.
    #[serde(rename = "load_factor", skip_serializing_if = "Option::is_none")]
    pub load_factor: Option<f64>,
    /// Number of meetings on the backend.
    #[serde(rename = "meetings_count", skip_serializing_if = "Option::is_none")]
    pub meetings_count: Option<i32>,
    /// The current state of the node.  **Example**: `ready`
    #[serde(rename = "node_state", skip_serializing_if = "Option::is_none")]
    pub node_state: Option<NodeState>,
    #[serde(rename = "settings", skip_serializing_if = "Option::is_none")]
    pub settings: Option<Box<models::BackendSettings>>,
    #[serde(rename = "synced_at", skip_serializing_if = "Option::is_none")]
    pub synced_at: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl BackendPatch {
    /// Backend Update
    pub fn new() -> BackendPatch {
        BackendPatch {
            admin_state: None,
            agent_heartbeat: None,
            agent_ref: None,
            attendees_count: None,
            bbb: None,
            created_at: None,
            id: None,
            last_error: None,
            latency: None,
            load_factor: None,
            meetings_count: None,
            node_state: None,
            settings: None,
            synced_at: None,
            updated_at: None,
        }
    }
}
/// The desired state of the node. If none given, it will be assumed 'ready'.  **Example**: `ready`
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AdminState {
    #[serde(rename = "init")]
    Init,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "stopped")]
    Stopped,
    #[serde(rename = "decommissioned")]
    Decommissioned,
}

impl Default for AdminState {
    fn default() -> AdminState {
        Self::Init
    }
}
/// The current state of the node.  **Example**: `ready`
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NodeState {
    #[serde(rename = "init")]
    Init,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "stopped")]
    Stopped,
    #[serde(rename = "decommissioned")]
    Decommissioned,
}

impl Default for NodeState {
    fn default() -> NodeState {
        Self::Init
    }
}
