/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BackendSettings : Backend Settings
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BackendSettings {
    /// The backend provides these tags. A frontend can require a list of tags. This can be used to dedicate parts of the cluster.
    #[serde(rename = "tags")]
    pub tags: Vec<String>,
}

impl BackendSettings {
    /// Backend Settings
    pub fn new(tags: Vec<String>) -> BackendSettings {
        BackendSettings { tags }
    }
}
