/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CommandRequest : Command Request
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommandRequest {
    /// The operation to perform.
    #[serde(rename = "action")]
    pub action: Action,
    /// Key value options for the command. See example above.
    #[serde(rename = "params")]
    pub params: std::collections::HashMap<String, String>,
}

impl CommandRequest {
    /// Command Request
    pub fn new(
        action: Action,
        params: std::collections::HashMap<String, String>,
    ) -> CommandRequest {
        CommandRequest { action, params }
    }
}
/// The operation to perform.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "end_all_meetings")]
    EndAllMeetings,
}

impl Default for Action {
    fn default() -> Action {
        Self::EndAllMeetings
    }
}
