/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Command : Command
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Command {
    /// The operation to perform.
    #[serde(rename = "action")]
    pub action: Action,
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// The commands need to be processed before the deadline is reached. The deadline is optional.
    #[serde(rename = "deadline")]
    pub deadline: String,
    #[serde(rename = "id")]
    pub id: String,
    /// Key value options for the command. See example above.
    #[serde(rename = "params")]
    pub params: std::collections::HashMap<String, String>,
    /// The result of the command. as key value object.
    #[serde(rename = "result", deserialize_with = "Option::deserialize")]
    pub result: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "seq")]
    pub seq: i32,
    #[serde(rename = "started_at", deserialize_with = "Option::deserialize")]
    pub started_at: Option<String>,
    /// The current state of the command.
    #[serde(rename = "state")]
    pub state: State,
    #[serde(rename = "stopped_at", deserialize_with = "Option::deserialize")]
    pub stopped_at: Option<String>,
}

impl Command {
    /// Command
    pub fn new(
        action: Action,
        created_at: String,
        deadline: String,
        id: String,
        params: std::collections::HashMap<String, String>,
        result: Option<std::collections::HashMap<String, String>>,
        seq: i32,
        started_at: Option<String>,
        state: State,
        stopped_at: Option<String>,
    ) -> Command {
        Command {
            action,
            created_at,
            deadline,
            id,
            params,
            result,
            seq,
            started_at,
            state,
            stopped_at,
        }
    }
}
/// The operation to perform.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "end_all_meetings")]
    EndAllMeetings,
}

impl Default for Action {
    fn default() -> Action {
        Self::EndAllMeetings
    }
}
/// The current state of the command.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "requested")]
    Requested,
    #[serde(rename = "success")]
    Success,
    #[serde(rename = "error")]
    Error,
}

impl Default for State {
    fn default() -> State {
        Self::Requested
    }
}
