/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DefaultPresentationSettings : Default Presentation
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DefaultPresentationSettings {
    /// Override any default presentation provided by the frontend.
    #[serde(rename = "force")]
    pub force: bool,
    /// An URL pointing to a default presentation.  **Example**: `https://assets.mycluster.example.com/tenant1235/presentation.pdf`
    #[serde(rename = "url")]
    pub url: String,
}

impl DefaultPresentationSettings {
    /// Default Presentation
    pub fn new(force: bool, url: String) -> DefaultPresentationSettings {
        DefaultPresentationSettings { force, url }
    }
}
