/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Format : Format
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Format {
    #[serde(rename = "Length")]
    pub length: i32,
    #[serde(rename = "Preview")]
    pub preview: Box<models::Preview>,
    #[serde(rename = "ProcessingTime")]
    pub processing_time: i32,
    #[serde(rename = "Type")]
    pub r#type: String,
    #[serde(rename = "URL")]
    pub url: String,
}

impl Format {
    /// Format
    pub fn new(
        length: i32,
        preview: models::Preview,
        processing_time: i32,
        r#type: String,
        url: String,
    ) -> Format {
        Format {
            length,
            preview: Box::new(preview),
            processing_time,
            r#type,
            url,
        }
    }
}
