/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FrontendConfig : A BBB frontend configuration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FrontendConfig {
    /// The tenant is identified by the key, which is part of frontend specific API url.  **Example**: `greenlight01`
    #[serde(rename = "key")]
    pub key: String,
    /// The individual BBB API secrect for this frontend. API requests coming from this frontend, must be signed with this secret.
    #[serde(rename = "secret")]
    pub secret: String,
}

impl FrontendConfig {
    /// A BBB frontend configuration
    pub fn new(key: String, secret: String) -> FrontendConfig {
        FrontendConfig { key, secret }
    }
}
