/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Frontend : Frontend
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Frontend {
    /// If not null, the frontend is bound to an account reference. The reference is freeform string. It is recommended to encode it as base64, but this is optional.
    #[serde(rename = "account_ref", deserialize_with = "Option::deserialize")]
    pub account_ref: Option<String>,
    /// When false, the frontend can not longer use the API.
    #[serde(rename = "active")]
    pub active: bool,
    #[serde(rename = "bbb")]
    pub bbb: Box<models::FrontendConfig>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "settings")]
    pub settings: Box<models::FrontendSettings>,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl Frontend {
    /// Frontend
    pub fn new(
        account_ref: Option<String>,
        active: bool,
        bbb: models::FrontendConfig,
        created_at: String,
        id: String,
        settings: models::FrontendSettings,
        updated_at: String,
    ) -> Frontend {
        Frontend {
            account_ref,
            active,
            bbb: Box::new(bbb),
            created_at,
            id,
            settings: Box::new(settings),
            updated_at,
        }
    }
}
