/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_json;

/// FrontendSettings : Frontend Settings
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FrontendSettings {
    #[serde(rename = "attendees_limit")]
    pub attendees_limit: Option<Box<models::AttendeesLimitSettings>>,
    /// Provide key value params, which will be used as a default when a meeting is created. See the BBB api documentation for which params are valid. The param value must be encoded as string.
    #[serde(rename = "create_default_params")]
    pub create_default_params: std::collections::HashMap<String, String>,
    /// A key value set of params which will override parameters from the frontend when a meeting is created.
    #[serde(rename = "create_override_params")]
    pub create_override_params: std::collections::HashMap<String, String>,
    #[serde(rename = "default_presentation")]
    pub default_presentation: Option<Box<models::DefaultPresentationSettings>>,
    /// When selecting a backend for creating a meeting, only consider nodes providing all of the required tags.
    #[serde(rename = "required_tags")]
    pub required_tags: Option<Vec<String>>,
    /// Recordings settings (ignored - for backwards compatibility with API)
    #[serde(rename = "recordings", skip_serializing)]
    pub recordings: Option<serde_json::Value>,
}

impl FrontendSettings {
    /// Frontend Settings
    pub fn new(
        attendees_limit: Option<models::AttendeesLimitSettings>,
        create_default_params: std::collections::HashMap<String, String>,
        create_override_params: std::collections::HashMap<String, String>,
        default_presentation: Option<models::DefaultPresentationSettings>,
        required_tags: Option<Vec<String>>,
    ) -> FrontendSettings {
        FrontendSettings {
            attendees_limit: attendees_limit.map(Box::new),
            create_default_params,
            create_override_params,
            default_presentation: default_presentation.map(Box::new),
            required_tags,
            recordings: None,
        }
    }
}
