/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FrontendSettings : Frontend Settings
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FrontendSettings {
    #[serde(rename = "attendees_limit")]
    pub attendees_limit: Box<models::AttendeesLimitSettings>,
    /// Provide key value params, which will be used as a default when a meeting is created. See the BBB api documentation for which params are valid. The param value must be encoded as string.
    #[serde(rename = "create_default_params")]
    pub create_default_params: std::collections::HashMap<String, String>,
    /// A key value set of params which will override parameters from the frontend when a meeting is created.
    #[serde(rename = "create_override_params")]
    pub create_override_params: std::collections::HashMap<String, String>,
    #[serde(rename = "default_presentation")]
    pub default_presentation: Box<models::DefaultPresentationSettings>,
    #[serde(rename = "recordings")]
    pub recordings: Box<models::RecordingsSettings>,
    /// When selecting a backend for creating a meeting, only consider nodes providing all of the required tags.
    #[serde(rename = "required_tags")]
    pub required_tags: Vec<String>,
}

impl FrontendSettings {
    /// Frontend Settings
    pub fn new(
        attendees_limit: models::AttendeesLimitSettings,
        create_default_params: std::collections::HashMap<String, String>,
        create_override_params: std::collections::HashMap<String, String>,
        default_presentation: models::DefaultPresentationSettings,
        recordings: models::RecordingsSettings,
        required_tags: Vec<String>,
    ) -> FrontendSettings {
        FrontendSettings {
            attendees_limit: Box::new(attendees_limit),
            create_default_params,
            create_override_params,
            default_presentation: Box::new(default_presentation),
            recordings: Box::new(recordings),
            required_tags,
        }
    }
}
