/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FrontendRequest : A Frontend Request
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FrontendRequest {
    /// If not null, the frontend is bound to an account reference. The reference is freeform string. It is recommended to encode it as base64, but this is optional.
    #[serde(
        rename = "account_ref",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_ref: Option<Option<String>>,
    /// When false, the frontend can not longer use the API.
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(rename = "bbb")]
    pub bbb: Box<models::FrontendConfig>,
    #[serde(rename = "settings", skip_serializing_if = "Option::is_none")]
    pub settings: Option<Box<models::FrontendSettings>>,
}

impl FrontendRequest {
    /// A Frontend Request
    pub fn new(bbb: models::FrontendConfig) -> FrontendRequest {
        FrontendRequest {
            account_ref: None,
            active: None,
            bbb: Box::new(bbb),
            settings: None,
        }
    }
}
