/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Heartbeat : Hearbeat
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Heartbeat {
    #[serde(rename = "backend_id")]
    pub backend_id: String,
    #[serde(rename = "heartbeat")]
    pub heartbeat: String,
}

impl Heartbeat {
    /// Hearbeat
    pub fn new(backend_id: String, heartbeat: String) -> Heartbeat {
        Heartbeat {
            backend_id,
            heartbeat,
        }
    }
}
