/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Images : Images
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Images {
    #[serde(rename = "All")]
    pub all: Vec<models::Image>,
}

impl Images {
    /// Images
    pub fn new(all: Vec<models::Image>) -> Images {
        Images { all }
    }
}
