/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Image : Image
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Image {
    #[serde(rename = "All", skip_serializing_if = "Option::is_none")]
    pub all: Option<Vec<models::Image>>,
}

impl Image {
    /// Image
    pub fn new() -> Image {
        Image { all: None }
    }
}
