/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MeetingInfoPatch : Meeting Info
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeetingInfoPatch {
    #[serde(rename = "AttendeePW", skip_serializing_if = "Option::is_none")]
    pub attendee_pw: Option<String>,
    #[serde(rename = "Attendees", skip_serializing_if = "Option::is_none")]
    pub attendees: Option<Vec<models::Attendee>>,
    #[serde(rename = "Breakout", skip_serializing_if = "Option::is_none")]
    pub breakout: Option<Box<models::Breakout>>,
    #[serde(rename = "BreakoutRooms", skip_serializing_if = "Option::is_none")]
    pub breakout_rooms: Option<Vec<String>>,
    #[serde(rename = "CreateDate", skip_serializing_if = "Option::is_none")]
    pub create_date: Option<String>,
    #[serde(rename = "CreateTime", skip_serializing_if = "Option::is_none")]
    pub create_time: Option<i32>,
    #[serde(rename = "DialNumber", skip_serializing_if = "Option::is_none")]
    pub dial_number: Option<String>,
    #[serde(rename = "Duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<i32>,
    #[serde(rename = "EndTime", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<i32>,
    #[serde(
        rename = "HasBeenForciblyEnded",
        skip_serializing_if = "Option::is_none"
    )]
    pub has_been_forcibly_ended: Option<bool>,
    #[serde(rename = "InternalMeetingID", skip_serializing_if = "Option::is_none")]
    pub internal_meeting_id: Option<String>,
    #[serde(rename = "IsBreakout", skip_serializing_if = "Option::is_none")]
    pub is_breakout: Option<bool>,
    #[serde(rename = "ListenerCount", skip_serializing_if = "Option::is_none")]
    pub listener_count: Option<i32>,
    #[serde(rename = "MaxUsers", skip_serializing_if = "Option::is_none")]
    pub max_users: Option<i32>,
    #[serde(rename = "MeetingID", skip_serializing_if = "Option::is_none")]
    pub meeting_id: Option<String>,
    #[serde(rename = "MeetingName", skip_serializing_if = "Option::is_none")]
    pub meeting_name: Option<String>,
    #[serde(rename = "Metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "ModeratorCount", skip_serializing_if = "Option::is_none")]
    pub moderator_count: Option<i32>,
    #[serde(rename = "ModeratorPW", skip_serializing_if = "Option::is_none")]
    pub moderator_pw: Option<String>,
    #[serde(rename = "ParticipantCount", skip_serializing_if = "Option::is_none")]
    pub participant_count: Option<i32>,
    #[serde(rename = "Recording", skip_serializing_if = "Option::is_none")]
    pub recording: Option<bool>,
    #[serde(rename = "Running", skip_serializing_if = "Option::is_none")]
    pub running: Option<bool>,
    #[serde(rename = "StartTime", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<i32>,
    #[serde(rename = "VideoCount", skip_serializing_if = "Option::is_none")]
    pub video_count: Option<i32>,
    #[serde(rename = "VoiceBridge", skip_serializing_if = "Option::is_none")]
    pub voice_bridge: Option<String>,
    #[serde(
        rename = "VoiceParticipantCount",
        skip_serializing_if = "Option::is_none"
    )]
    pub voice_participant_count: Option<i32>,
}

impl MeetingInfoPatch {
    /// Meeting Info
    pub fn new() -> MeetingInfoPatch {
        MeetingInfoPatch {
            attendee_pw: None,
            attendees: None,
            breakout: None,
            breakout_rooms: None,
            create_date: None,
            create_time: None,
            dial_number: None,
            duration: None,
            end_time: None,
            has_been_forcibly_ended: None,
            internal_meeting_id: None,
            is_breakout: None,
            listener_count: None,
            max_users: None,
            meeting_id: None,
            meeting_name: None,
            metadata: None,
            moderator_count: None,
            moderator_pw: None,
            participant_count: None,
            recording: None,
            running: None,
            start_time: None,
            video_count: None,
            voice_bridge: None,
            voice_participant_count: None,
        }
    }
}
