/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MeetingInfo : Meeting Info
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeetingInfo {
    #[serde(rename = "AttendeePW")]
    pub attendee_pw: String,
    #[serde(rename = "Attendees")]
    pub attendees: Vec<models::Attendee>,
    #[serde(rename = "Breakout")]
    pub breakout: Box<models::Breakout>,
    #[serde(rename = "BreakoutRooms")]
    pub breakout_rooms: Vec<String>,
    #[serde(rename = "CreateDate")]
    pub create_date: String,
    #[serde(rename = "CreateTime")]
    pub create_time: i32,
    #[serde(rename = "DialNumber")]
    pub dial_number: String,
    #[serde(rename = "Duration")]
    pub duration: i32,
    #[serde(rename = "EndTime")]
    pub end_time: i32,
    #[serde(rename = "HasBeenForciblyEnded")]
    pub has_been_forcibly_ended: bool,
    #[serde(rename = "InternalMeetingID")]
    pub internal_meeting_id: String,
    #[serde(rename = "IsBreakout")]
    pub is_breakout: bool,
    #[serde(rename = "ListenerCount")]
    pub listener_count: i32,
    #[serde(rename = "MaxUsers")]
    pub max_users: i32,
    #[serde(rename = "MeetingID")]
    pub meeting_id: String,
    #[serde(rename = "MeetingName")]
    pub meeting_name: String,
    #[serde(rename = "Metadata")]
    pub metadata: std::collections::HashMap<String, String>,
    #[serde(rename = "ModeratorCount")]
    pub moderator_count: i32,
    #[serde(rename = "ModeratorPW")]
    pub moderator_pw: String,
    #[serde(rename = "ParticipantCount")]
    pub participant_count: i32,
    #[serde(rename = "Recording")]
    pub recording: bool,
    #[serde(rename = "Running")]
    pub running: bool,
    #[serde(rename = "StartTime")]
    pub start_time: i32,
    #[serde(rename = "VideoCount")]
    pub video_count: i32,
    #[serde(rename = "VoiceBridge")]
    pub voice_bridge: String,
    #[serde(rename = "VoiceParticipantCount")]
    pub voice_participant_count: i32,
}

impl MeetingInfo {
    /// Meeting Info
    pub fn new(
        attendee_pw: String,
        attendees: Vec<models::Attendee>,
        breakout: models::Breakout,
        breakout_rooms: Vec<String>,
        create_date: String,
        create_time: i32,
        dial_number: String,
        duration: i32,
        end_time: i32,
        has_been_forcibly_ended: bool,
        internal_meeting_id: String,
        is_breakout: bool,
        listener_count: i32,
        max_users: i32,
        meeting_id: String,
        meeting_name: String,
        metadata: std::collections::HashMap<String, String>,
        moderator_count: i32,
        moderator_pw: String,
        participant_count: i32,
        recording: bool,
        running: bool,
        start_time: i32,
        video_count: i32,
        voice_bridge: String,
        voice_participant_count: i32,
    ) -> MeetingInfo {
        MeetingInfo {
            attendee_pw,
            attendees,
            breakout: Box::new(breakout),
            breakout_rooms,
            create_date,
            create_time,
            dial_number,
            duration,
            end_time,
            has_been_forcibly_ended,
            internal_meeting_id,
            is_breakout,
            listener_count,
            max_users,
            meeting_id,
            meeting_name,
            metadata,
            moderator_count,
            moderator_pw,
            participant_count,
            recording,
            running,
            start_time,
            video_count,
            voice_bridge,
            voice_participant_count,
        }
    }
}
