/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MigrationState : MigrationState
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MigrationState {
    #[serde(rename = "applied_at")]
    pub applied_at: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "version")]
    pub version: i32,
}

impl MigrationState {
    /// MigrationState
    pub fn new(applied_at: String, description: String, version: i32) -> MigrationState {
        MigrationState {
            applied_at,
            description,
            version,
        }
    }
}
