/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NotFoundError : The requested resource could not be found
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotFoundError {
    /// An error type tag. See specific error for details.
    #[serde(rename = "error")]
    pub error: String,
    /// A human readable message with details about the error.
    #[serde(rename = "message")]
    pub message: String,
}

impl NotFoundError {
    /// The requested resource could not be found
    pub fn new(error: String, message: String) -> NotFoundError {
        NotFoundError { error, message }
    }
}
