/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Preview : Preview
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Preview {
    #[serde(rename = "Images")]
    pub images: Box<models::Images>,
}

impl Preview {
    /// Preview
    pub fn new(images: models::Images) -> Preview {
        Preview {
            images: Box::new(images),
        }
    }
}
