/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Recording : Recording
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Recording {
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// The id of the associated frontend.
    #[serde(rename = "frontend_id")]
    pub frontend_id: String,
    /// The internal meeting id.
    #[serde(rename = "internal_meeting_id")]
    pub internal_meeting_id: String,
    /// The id of the related meeting.
    #[serde(rename = "meeting_id")]
    pub meeting_id: String,
    /// ID of the recording.
    #[serde(rename = "record_id")]
    pub record_id: String,
    #[serde(rename = "recording")]
    pub recording: Box<models::RecordingData>,
    #[serde(rename = "synced_at")]
    pub synced_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl Recording {
    /// Recording
    pub fn new(
        created_at: String,
        frontend_id: String,
        internal_meeting_id: String,
        meeting_id: String,
        record_id: String,
        recording: models::RecordingData,
        synced_at: String,
        updated_at: String,
    ) -> Recording {
        Recording {
            created_at,
            frontend_id,
            internal_meeting_id,
            meeting_id,
            record_id,
            recording: Box::new(recording),
            synced_at,
            updated_at,
        }
    }
}
