/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RecordingData : Recording
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecordingData {
    #[serde(rename = "EndTime")]
    pub end_time: i32,
    #[serde(rename = "Formats")]
    pub formats: Vec<models::Format>,
    #[serde(rename = "InternalMeetingID")]
    pub internal_meeting_id: String,
    #[serde(rename = "IsBreakout")]
    pub is_breakout: bool,
    #[serde(rename = "MeetingID")]
    pub meeting_id: String,
    #[serde(rename = "Metadata")]
    pub metadata: std::collections::HashMap<String, String>,
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "Participants")]
    pub participants: i32,
    #[serde(rename = "Published")]
    pub published: bool,
    #[serde(rename = "RecordID")]
    pub record_id: String,
    #[serde(rename = "StartTime")]
    pub start_time: i32,
    #[serde(rename = "State")]
    pub state: String,
}

impl RecordingData {
    /// Recording
    pub fn new(
        end_time: i32,
        formats: Vec<models::Format>,
        internal_meeting_id: String,
        is_breakout: bool,
        meeting_id: String,
        metadata: std::collections::HashMap<String, String>,
        name: String,
        participants: i32,
        published: bool,
        record_id: String,
        start_time: i32,
        state: String,
    ) -> RecordingData {
        RecordingData {
            end_time,
            formats,
            internal_meeting_id,
            is_breakout,
            meeting_id,
            metadata,
            name,
            participants,
            published,
            record_id,
            start_time,
            state,
        }
    }
}
