/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RecordingVisibilityUpdate : RecordingVisibilityUpdate
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecordingVisibilityUpdate {
    /// The ID of the recording. (RecordID)
    #[serde(rename = "record_id")]
    pub record_id: String,
    /// The new visibilty.
    #[serde(rename = "visibility")]
    pub visibility: i32,
}

impl RecordingVisibilityUpdate {
    /// RecordingVisibilityUpdate
    pub fn new(record_id: String, visibility: i32) -> RecordingVisibilityUpdate {
        RecordingVisibilityUpdate {
            record_id,
            visibility,
        }
    }
}
