/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RecordingsSettings : Recordings Settings
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecordingsSettings {
    /// Recordings created by this frontend will have this visibility when imported.
    #[serde(rename = "visibility_override")]
    pub visibility_override: i32,
}

impl RecordingsSettings {
    /// Recordings Settings
    pub fn new(visibility_override: i32) -> RecordingsSettings {
        RecordingsSettings {
            visibility_override,
        }
    }
}
