/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcResponse : RPCResponse Envelope
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcResponse {
    /// An object with the encoded result of the call.
    #[serde(rename = "result")]
    pub result: std::collections::HashMap<String, serde_json::Value>,
    /// The name of the procedure to invoke.
    #[serde(rename = "status")]
    pub status: Status,
}

impl RpcResponse {
    /// RPCResponse Envelope
    pub fn new(
        result: std::collections::HashMap<String, serde_json::Value>,
        status: Status,
    ) -> RpcResponse {
        RpcResponse { result, status }
    }
}
/// The name of the procedure to invoke.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "ok")]
    Ok,
    #[serde(rename = "error")]
    Error,
}

impl Default for Status {
    fn default() -> Status {
        Self::Ok
    }
}
