/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcRequest : RPCRequest Envelope
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcRequest {
    /// The name of the procedure to invoke.
    #[serde(rename = "action")]
    pub action: String,
    /// An object with the RPC request parameters.
    #[serde(rename = "payload")]
    pub payload: std::collections::HashMap<String, serde_json::Value>,
}

impl RpcRequest {
    /// RPCRequest Envelope
    pub fn new(
        action: String,
        payload: std::collections::HashMap<String, serde_json::Value>,
    ) -> RpcRequest {
        RpcRequest { action, payload }
    }
}
