/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SchemaStatus : SchemaStatus
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SchemaStatus {
    #[serde(rename = "available")]
    pub available: bool,
    #[serde(rename = "database")]
    pub database: String,
    #[serde(rename = "error", deserialize_with = "Option::deserialize")]
    pub error: Option<String>,
    #[serde(rename = "migrated")]
    pub migrated: bool,
    #[serde(rename = "migration")]
    pub migration: Box<models::MigrationState>,
    #[serde(rename = "pending_migrations")]
    pub pending_migrations: i32,
}

impl SchemaStatus {
    /// SchemaStatus
    pub fn new(
        available: bool,
        database: String,
        error: Option<String>,
        migrated: bool,
        migration: models::MigrationState,
        pending_migrations: i32,
    ) -> SchemaStatus {
        SchemaStatus {
            available,
            database,
            error,
            migrated,
            migration: Box::new(migration),
            pending_migrations,
        }
    }
}
