/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ServerError : A Server Error
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerError {
    /// A human readable message with details about the error.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl ServerError {
    /// A Server Error
    pub fn new() -> ServerError {
        ServerError { message: None }
    }
}
