/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Status : Server Status
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Status {
    /// The currently authenticated subject.
    #[serde(rename = "account_ref")]
    pub account_ref: String,
    /// The API version.  **Example**: `v1`
    #[serde(rename = "api")]
    pub api: String,
    /// Build identifier of the server.
    #[serde(rename = "build")]
    pub build: String,
    #[serde(rename = "database")]
    pub database: Box<models::SchemaStatus>,
    /// True if the subject has admin privileges.
    #[serde(rename = "is_admin")]
    pub is_admin: bool,
    /// The current b3scale server version.
    #[serde(rename = "version")]
    pub version: String,
}

impl Status {
    /// Server Status
    pub fn new(
        account_ref: String,
        api: String,
        build: String,
        database: models::SchemaStatus,
        is_admin: bool,
        version: String,
    ) -> Status {
        Status {
            account_ref,
            api,
            build,
            database: Box::new(database),
            is_admin,
            version,
        }
    }
}
