/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

/// BackendSettings : Backend Settings 



#[derive(Clone, Debug, PartialEq, Default, serde::Serialize, serde::Deserialize)]
pub struct BackendSettings {
    /// The backend provides these tags. A frontend can require a list of tags. This can be used to dedicate parts of the cluster.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}

impl BackendSettings {
    /// Backend Settings 
    pub fn new() -> BackendSettings {
        BackendSettings {
            tags: None,
        }
    }
}


