/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

/// Backend : Backend



#[derive(Clone, Debug, PartialEq, Default, serde::Serialize, serde::Deserialize)]
pub struct Backend {
    /// The desired state of the node. If none given, it will be assumed 'ready'.  **Example**: `ready`
    #[serde(rename = "admin_state")]
    pub admin_state: AdminState,
    /// The last time we heared from the node agent.
    #[serde(rename = "agent_heartbeat")]
    pub agent_heartbeat: String,
    /// The identifier of the agent running on the backend. Used for backend authorization and agent authentication.
    #[serde(rename = "agent_ref")]
    pub agent_ref: Option<String>,
    /// Number of participants in meetings on the backend.
    #[serde(rename = "attendees_count")]
    pub attendees_count: i32,
    #[serde(rename = "bbb")]
    pub bbb: Box<crate::api::models::BackendConfig>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: String,
    /// The last error that happend. For example destination host not reachable.
    #[serde(rename = "last_error")]
    pub last_error: Option<String>,
    /// The amount of milliseconds when polling the current node state.
    #[serde(rename = "latency")]
    pub latency: i32,
    /// The load factor influences the probability of selecting this backend when a meeting is created. The amount of meetings and attendees on the node will be multiplied with the load factor, when calculating the backend stress.
    #[serde(rename = "load_factor")]
    pub load_factor: f32,
    /// Number of meetings on the backend.
    #[serde(rename = "meetings_count")]
    pub meetings_count: i32,
    /// The current state of the node.  **Example**: `ready`
    #[serde(rename = "node_state")]
    pub node_state: NodeState,
    #[serde(rename = "settings")]
    pub settings: Box<crate::api::models::BackendSettings>,
    #[serde(rename = "synced_at")]
    pub synced_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl Backend {
    /// Backend
    pub fn new(admin_state: AdminState, agent_heartbeat: String, agent_ref: Option<String>, attendees_count: i32, bbb: crate::api::models::BackendConfig, created_at: String, id: String, last_error: Option<String>, latency: i32, load_factor: f32, meetings_count: i32, node_state: NodeState, settings: crate::api::models::BackendSettings, synced_at: String, updated_at: String) -> Backend {
        Backend {
            admin_state,
            agent_heartbeat,
            agent_ref,
            attendees_count,
            bbb: Box::new(bbb),
            created_at,
            id,
            last_error,
            latency,
            load_factor,
            meetings_count,
            node_state,
            settings: Box::new(settings),
            synced_at,
            updated_at,
        }
    }
}

/// The desired state of the node. If none given, it will be assumed 'ready'.  **Example**: `ready`
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, serde::Serialize, serde::Deserialize)]
pub enum AdminState {
    #[serde(rename = "init")]
    Init,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "stopped")]
    Stopped,
    #[serde(rename = "decommissioned")]
    Decommissioned,
}

impl Default for AdminState {
    fn default() -> AdminState {
        Self::Init
    }
}
/// The current state of the node.  **Example**: `ready`
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, serde::Serialize, serde::Deserialize)]
pub enum NodeState {
    #[serde(rename = "init")]
    Init,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "stopped")]
    Stopped,
    #[serde(rename = "decommissioned")]
    Decommissioned,
}

impl Default for NodeState {
    fn default() -> NodeState {
        Self::Init
    }
}

