/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

/// BackendConfig : Backend Config



#[derive(Clone, Debug, PartialEq, Default, serde::Serialize, serde::Deserialize)]
pub struct BackendConfig {
    /// The full qualified address of the host, including the API endpoint.  **Example**: `https://backendnode01/bigbluebutton/api/`
    #[serde(rename = "host")]
    pub host: String,
    /// The API secret for the BBB host.
    #[serde(rename = "secret")]
    pub secret: String,
}

impl BackendConfig {
    /// Backend Config
    pub fn new(host: String, secret: String) -> BackendConfig {
        BackendConfig {
            host,
            secret,
        }
    }
}


