/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

/// BackendRequest : Backend Request



#[derive(Clone, Debug, PartialEq, Default, serde::Serialize, serde::Deserialize)]
pub struct BackendRequest {
    /// The desired state of the node. If none given, it will be assumed 'ready'.  **Example**: `ready`
    #[serde(rename = "admin_state", skip_serializing_if = "Option::is_none")]
    pub admin_state: Option<AdminState>,
    #[serde(rename = "bbb")]
    pub bbb: Box<crate::api::models::BackendConfig>,
    /// The load factor influences the probability of selecting this backend when a meeting is created. The amount of meetings and attendees on the node will be multiplied with the load factor, when calculating the backend stress.
    #[serde(rename = "load_factor", skip_serializing_if = "Option::is_none")]
    pub load_factor: Option<f32>,
    #[serde(rename = "settings", skip_serializing_if = "Option::is_none")]
    pub settings: Option<Box<crate::api::models::BackendSettings>>,
}

impl BackendRequest {
    /// Backend Request
    pub fn new(bbb: crate::api::models::BackendConfig) -> BackendRequest {
        BackendRequest {
            admin_state: None,
            bbb: Box::new(bbb),
            load_factor: None,
            settings: None,
        }
    }
}

/// The desired state of the node. If none given, it will be assumed 'ready'.  **Example**: `ready`
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, serde::Serialize, serde::Deserialize)]
pub enum AdminState {
    #[serde(rename = "init")]
    Init,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "stopped")]
    Stopped,
    #[serde(rename = "decommissioned")]
    Decommissioned,
}

impl Default for AdminState {
    fn default() -> AdminState {
        Self::Init
    }
}

