/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

/// Breakout : Meeting Breakout Room



#[derive(Clone, Debug, PartialEq, Default, serde::Serialize, serde::Deserialize)]
pub struct Breakout {
    #[serde(rename = "FreeJoin")]
    pub free_join: bool,
    #[serde(rename = "ParentMeetingID")]
    pub parent_meeting_id: String,
    #[serde(rename = "Sequence")]
    pub sequence: i32,
}

impl Breakout {
    /// Meeting Breakout Room
    pub fn new(free_join: bool, parent_meeting_id: String, sequence: i32) -> Breakout {
        Breakout {
            free_join,
            parent_meeting_id,
            sequence,
        }
    }
}


