/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

/// FrontendConfigPatch : A BBB frontend configuration



#[derive(Clone, Debug, PartialEq, Default, serde::Serialize, serde::Deserialize)]
pub struct FrontendConfigPatch {
    /// The tenant is identified by the key, which is part of frontend specific API url.  **Example**: `greenlight01`
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// The individual BBB API secrect for this frontend. API requests coming from this frontend, must be signed with this secret.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
}

impl FrontendConfigPatch {
    /// A BBB frontend configuration
    pub fn new() -> FrontendConfigPatch {
        FrontendConfigPatch {
            key: None,
            secret: None,
        }
    }
}


