/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

/// FrontendSettings : Frontend Settings

#[derive(Clone, Debug, PartialEq, Default, serde::Serialize, serde::Deserialize)]
pub struct FrontendSettings {
    /// Provide key value params, which will be used as a default when a meeting is created. See the BBB api documentation for which params are valid. The param value must be encoded as string.
    #[serde(
        rename = "create_default_params",
        skip_serializing_if = "Option::is_none"
    )]
    pub create_default_params: Option<::std::collections::HashMap<String, String>>,
    /// A key value set of params which will override parameters from the frontend when a meeting is created.
    #[serde(
        rename = "create_override_params",
        skip_serializing_if = "Option::is_none"
    )]
    pub create_override_params: Option<::std::collections::HashMap<String, String>>,
    #[serde(
        rename = "default_presentation",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_presentation: Option<Box<crate::api::models::DefaultPresentationSettings>>,
    /// When selecting a backend for creating a meeting, only consider nodes providing all of the required tags.
    #[serde(rename = "required_tags", skip_serializing_if = "Option::is_none")]
    pub required_tags: Option<Vec<String>>,
}

impl FrontendSettings {
    /// Frontend Settings
    pub fn new() -> FrontendSettings {
        FrontendSettings {
            create_default_params: None,
            create_override_params: None,
            default_presentation: None,
            required_tags: None,
        }
    }
}
