/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

/// FrontendPatch : A Frontend Update



#[derive(Clone, Debug, PartialEq, Default, serde::Serialize, serde::Deserialize)]
pub struct FrontendPatch {
    /// If not null, the frontend is bound to an account reference. The reference is freeform string. It is recommended to encode it as base64, but this is optional.
    #[serde(rename = "account_ref", skip_serializing_if = "Option::is_none")]
    pub account_ref: Option<String>,
    /// When false, the frontend can not longer use the API.
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(rename = "bbb", skip_serializing_if = "Option::is_none")]
    pub bbb: Option<Box<crate::api::models::FrontendConfigPatch>>,
    #[serde(rename = "settings", skip_serializing_if = "Option::is_none")]
    pub settings: Option<Box<crate::api::models::FrontendSettings>>,
}

impl FrontendPatch {
    /// A Frontend Update
    pub fn new() -> FrontendPatch {
        FrontendPatch {
            account_ref: None,
            active: None,
            bbb: None,
            settings: None,
        }
    }
}


