/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

/// Images : Images



#[derive(Clone, Debug, PartialEq, Default, serde::Serialize, serde::Deserialize)]
pub struct Images {
    #[serde(rename = "All")]
    pub all: Vec<crate::api::models::Image>,
}

impl Images {
    /// Images
    pub fn new(all: Vec<crate::api::models::Image>) -> Images {
        Images {
            all,
        }
    }
}


