/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

/// Image : Image



#[derive(Clone, Debug, PartialEq, Default, serde::Serialize, serde::Deserialize)]
pub struct Image {
    #[serde(rename = "All", skip_serializing_if = "Option::is_none")]
    pub all: Option<Vec<crate::api::models::Image>>,
}

impl Image {
    /// Image
    pub fn new() -> Image {
        Image {
            all: None,
        }
    }
}


