/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

/// Meeting : Meeting



#[derive(Clone, Debug, PartialEq, Default, serde::Serialize, serde::Deserialize)]
pub struct Meeting {
    #[serde(rename = "backend_id")]
    pub backend_id: Option<String>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "frontend_id")]
    pub frontend_id: Option<String>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "internal_id")]
    pub internal_id: String,
    #[serde(rename = "meeting")]
    pub meeting: Box<crate::api::models::MeetingInfo>,
    #[serde(rename = "synced_at")]
    pub synced_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl Meeting {
    /// Meeting
    pub fn new(backend_id: Option<String>, created_at: String, frontend_id: Option<String>, id: String, internal_id: String, meeting: crate::api::models::MeetingInfo, synced_at: String, updated_at: String) -> Meeting {
        Meeting {
            backend_id,
            created_at,
            frontend_id,
            id,
            internal_id,
            meeting: Box::new(meeting),
            synced_at,
            updated_at,
        }
    }
}


