/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

/// MeetingPatch : Meeting Update



#[derive(Clone, Debug, PartialEq, Default, serde::Serialize, serde::Deserialize)]
pub struct MeetingPatch {
    #[serde(rename = "meeting")]
    pub meeting: Box<crate::api::models::MeetingInfoPatch>,
}

impl MeetingPatch {
    /// Meeting Update
    pub fn new(meeting: crate::api::models::MeetingInfoPatch) -> MeetingPatch {
        MeetingPatch {
            meeting: Box::new(meeting),
        }
    }
}


