/*
 * b3scale api v1
 *
 * This document describes the specifications for the b3scale API v1.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: mail@infra.run
 * Generated by: https://openapi-generator.tech
 */

/// ValidationError : Request validation failed.The error type is: `validation_error`



#[derive(Clone, Debug, PartialEq, Default, serde::Serialize, serde::Deserialize)]
pub struct ValidationError {
    /// An error type tag. See specific error for details.
    #[serde(rename = "error")]
    pub error: String,
    /// A human readable message with details about the error.
    #[serde(rename = "message")]
    pub message: String,
}

impl ValidationError {
    /// Request validation failed.The error type is: `validation_error`
    pub fn new(error: String, message: String) -> ValidationError {
        ValidationError {
            error,
            message,
        }
    }
}


